"""corpus content hash

Revision ID: a64944e4659d
Revises: c52d299de6b7
Create Date: 2026-09-17 02:39:52.553165+08:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a64944e4659d'
down_revision = 'c52d299de6b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corpus_chunks', sa.Column('content_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corpus_chunks', 'content_hash')
    # ### end Alembic commands ###
