"""initial schema

Revision ID: c52d299de6b7
Revises: 
Create Date: 2026-09-17 02:08:33.469973+08:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = 'c52d299de6b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_chunks',
    sa.Column('doc_id', sa.String(length=160), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('object', sa.String(length=120), nullable=True),
    sa.Column('era', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('authority', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedder', sa.String(length=64), nullable=False),
    # 维度必须与 settings.vector_dim 一致；改维度用
    #   python scripts/migrate.py --recreate-vectors
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('ix_corpus_embedder', 'corpus_chunks', ['embedder'], unique=False)
    op.create_index('ix_corpus_embedding_hnsw', 'corpus_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_index('ix_corpus_object', 'corpus_chunks', ['object'], unique=False)
    op.create_table('restoration_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('item', sa.String(length=120), nullable=True),
    sa.Column('identity', sa.String(length=120), nullable=True),
    sa.Column('scene', sa.String(length=120), nullable=True),
    sa.Column('style', sa.String(length=120), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=True),
    sa.Column('profile_key', sa.String(length=64), nullable=True),
    sa.Column('material_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('objective_score', sa.Float(), nullable=True),
    sa.Column('judge_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('revisions', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=True),
    sa.Column('image_degraded', sa.Boolean(), nullable=False),
    sa.Column('qa_skipped', sa.Boolean(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('degraded_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_restoration_tasks_decision'), 'restoration_tasks', ['decision'], unique=False)
    op.create_index(op.f('ix_restoration_tasks_kind'), 'restoration_tasks', ['kind'], unique=False)
    op.create_index(op.f('ix_restoration_tasks_profile_key'), 'restoration_tasks', ['profile_key'], unique=False)
    op.create_index('ix_tasks_created_at', 'restoration_tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_kind_decision', 'restoration_tasks', ['kind', 'decision'], unique=False)
    op.create_table('qa_verdicts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('objective_score', sa.Float(), nullable=True),
    sa.Column('judge_score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('anachronisms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('violated_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('material_key', sa.String(length=64), nullable=True),
    sa.Column('profile_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['restoration_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'round_index', name='uq_qa_verdicts_round')
    )
    op.create_index('ix_qa_score', 'qa_verdicts', ['score'], unique=False)
    op.create_index(op.f('ix_qa_verdicts_decision'), 'qa_verdicts', ['decision'], unique=False)
    op.create_table('task_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('bytes_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['restoration_tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'round_index', name='uq_task_images_round')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_images')
    op.drop_index(op.f('ix_qa_verdicts_decision'), table_name='qa_verdicts')
    op.drop_index('ix_qa_score', table_name='qa_verdicts')
    op.drop_table('qa_verdicts')
    op.drop_index('ix_tasks_kind_decision', table_name='restoration_tasks')
    op.drop_index('ix_tasks_created_at', table_name='restoration_tasks')
    op.drop_index(op.f('ix_restoration_tasks_profile_key'), table_name='restoration_tasks')
    op.drop_index(op.f('ix_restoration_tasks_kind'), table_name='restoration_tasks')
    op.drop_index(op.f('ix_restoration_tasks_decision'), table_name='restoration_tasks')
    op.drop_table('restoration_tasks')
    op.drop_index('ix_corpus_object', table_name='corpus_chunks')
    op.drop_index('ix_corpus_embedding_hnsw', table_name='corpus_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_index('ix_corpus_embedder', table_name='corpus_chunks')
    op.drop_table('corpus_chunks')
    # ### end Alembic commands ###
